library("devtools")

ignore <- c(
  # "AnnotationDbi",
  "AnnotationForge",
  "AnnotationHub",
  "AnnotationHubData",
  "APSIM",
  "archivist",
  # "BatchExperiments",
  # "BatchJobs",
  "bibliospec",
  "biglm",
  # "bioassayR",
  "caroline",
  # "Category",
  "ChemmineR",
  "chunked",
  "CITAN",
  "clstutils",
  "CNEr",
  "CollapsABEL",
  # "cummeRbund",
  "customProDB",
  "DBI",
  # "DECIPHER",
  "dplyr",
  "ecd",
  "emuR",
  "ENCODExplorer",
  "ensembldb",
  "etl",
  "ETLUtils",
  "filehashSQLite",
  "filematrix",
  "freqweights",
  "gcbd",
  "GeneAnswers",
  "GenomicFeatures",
  # "Genominator",
  "GEOmetadb",
  # "GWASTools",
  "imputeMulti",
  "iontree",
  "lumi",
  "macleish",
  "maGUI",
  "manta",
  "marmap",
  "MeSHDbi",
  "metagenomeFeatures",
  "MetaIntegrator",
  "metaseqR",
  # "mgsa",
  "miRNAtap",
  "MmPalateMiRNA",
  "MonetDBLite",
  "MUCflights",
  "nutshell",
  "nutshell.bbdb",
  "oai",
  "oce",
  # "oligo",
  "oligoClasses",
  "OrganismDbi",
  # "PAnnBuilder",
  # "pdInfoBuilder",
  "PGA",
  "pitchRx",
  # "plethy",
  # "poplite",
  # "ProjectTemplate",
  "quantmod",
  # "rangeMapper",
  # "RecordLinkage",
  "recordr",
  "recoup",
  "refGenome",
  "rgrass7",
  "RImmPort",
  # "RObsDat",
  # "rplexos",
  "RQDA",
  "rTRM",
  "rvertnet",
  "scrime",
  "SEERaBomb",
  "seqplots",
  "SGP",
  "smnet",
  "snplist",
  # "specL",
  # "sqldf",
  "sqliter",
  "SRAdb",
  "SSN",
  "storr",
  "stream",
  "survey",
  "taRifx",
  # "tcpl",
  # "TFBSTools",
  # "tigre",
  "trackeR",
  "TSdata",
  "TSsql",
  "TSSQLite",
  "tweet2r",
  "twitteR",
  # "UniProt.ws",
  "Uniquorn",
  "UPMASK",
  # "VariantFiltering",
  "vegdata",
  "vmsbase"
)

revdep_check(threads = parallel::detectCores(), bioconductor = TRUE, ignore = ignore)
revdep_check_save_summary()
