#ifndef RSQLITE_COLUMNDATATYPE_H
#define RSQLITE_COLUMNDATATYPE_H

enum DATA_TYPE {
  DT_UNKNOWN = NILSXP,
  DT_INT = INTSXP,
  DT_REAL = REALSXP,
  DT_STRING = STRSXP,
  DT_BLOB = VECSXP,
};

#endif // RSQLITE_COLUMNDATATYPE_H
