#ifndef RSQLITE_COLUMNDATATYPE_H
#define RSQLITE_COLUMNDATATYPE_H

#include <Rcpp.h>

enum DATA_TYPE {
  DT_UNKNOWN = NILSXP,
  DT_BOOL = LGLSXP,
  DT_INT = INTSXP,
  DT_REAL = REALSXP,
  DT_STRING = STRSXP,
  DT_BLOB = VECSXP
};

#endif // RSQLITE_COLUMNDATATYPE_H
