#' @include Connection.R
#' @include Driver.R
NULL

#' Connect to/disconnect from a SQLite database.
#' 
#' @param drv An objected generated by \code{\link{SQLite}}, or an existing
#'   \code{\linkS4class{SQLiteConnection}}. If an connection, the connection
#'   will be cloned.
#' @param dbname The path to the database file. If the value is an empty
#'   string (\code{""}), then a temporary on-disk database is created. The
#'   temporary file will be deleted when the connection is closed. If the
#'   value is \code{":memory:"}, then an temporary in-memory only database
#'   is created.
#' @param cache_size Advanced option. A positive integer to change the maximum 
#'   number of disk pages that SQLite holds in memory (SQLite's default is 
#'   2000 pages). See \url{http://www.sqlite.org/pragma.html#pragma_cache_size} 
#'   for details.
#' @param synchronous Advanced options. Possible values for \code{synchronous} 
#'   are 0 (the default), 1, or 2 or the corresponding strings "OFF", "NORMAL", 
#'   or  "FULL".  Users have reported significant speed ups using 
#'   \code{sychronous=0}, and the SQLite documentation itself implies 
#'   considerable improved performance at the very modest risk of database 
#'   corruption in the unlikely case of the operating system (\emph{not} the 
#'   R application) crashing. See the SQLite documentation for the full details 
#'   of this \code{PRAGMA}. See 
#'   \url{http://www.sqlite.org/pragma.html#pragma_synchronous} for details.
#' @param flags \code{SQLITE_RWC}: open the database in read/write mode
#'   and create the database file if it does not already exist; 
#'   \code{SQLITE_RW}: open the database in read/write mode. Raise an error 
#'   if the file does not already exist; \code{SQLITE_RO}: open the database in 
#'   read only mode.  Raise an error if the file does not already exist
#' @param loadable.extensions When \code{TRUE} (default) SQLite3
#'   loadable extensions are enabled. Setting this value to \code{FALSE}
#'   prevents extensions from being loaded.
#' @param vfs Select the SQLite3 OS interface. See
#'   \url{http://www.sqlite.org/vfs.html} for details. Allowed values are
#'   \code{"unix-posix"}, \code{"unix-unix-afp"},
#'   \code{"unix-unix-flock"}, \code{"unix-dotfile"}, and
#'   \code{"unix-none"}.
#' @aliases SQLITE_RWC SQLITE_RW SQLITE_RO
#' @export
#' @useDynLib RSQLite RS_SQLite_newConnection
setMethod("dbConnect", "SQLiteDriver",
  function(drv, dbname = "", loadable.extensions = TRUE, cache_size = NULL, 
    synchronous = 0, flags = NULL, vfs = NULL) {
    if (is.null(dbname))
      dbname <- ""
    ## path.expand converts as.character(NA) => "NA"
    if (any(is.na(dbname)))
      stop("'dbname' must not be NA")
    dbname <- path.expand(dbname)
    loadable.extensions <- as.logical(loadable.extensions)
    if (!is.null(vfs)) {
      if (.Platform[["OS.type"]] == "windows") {
        warning("vfs customization not available on this platform.",
          " Ignoring value: vfs = ", vfs)
      } else {
        if (length(vfs) != 1L)
          stop("'vfs' must be NULL or a character vector of length one")
        allowed <- c("unix-posix", "unix-afp", "unix-flock", "unix-dotfile",
          "unix-none")
        if (!(vfs %in% allowed)) {
          stop("'vfs' must be one of ",
            paste(allowed, collapse=", "),
            ". See http://www.sqlite.org/compile.html")
        }
      }
    }
    flags <- if (is.null(flags)) SQLITE_RWC else flags
    drvId <- drv@Id
    conId <- .Call(RS_SQLite_newConnection, drvId, dbname, loadable.extensions, 
      flags, vfs)
    con <- new("SQLiteConnection", Id = conId)
    
    ## experimental PRAGMAs
    try({
      if(!is.null(cache_size))
        dbGetQuery(con, sprintf("PRAGMA cache_size=%d", as.integer(cache_size)))
      
      if (is.numeric(synchronous)) {
        nsync <- as.integer(synchronous)
      } else if(is.character(synchronous)) {
        nsync <- pmatch(tolower(synchronous), c("off", "normal", "full"), 
          nomatch = 1) - 1
      } else {
        nsync <- 0
      }
      dbGetQuery(con, sprintf("PRAGMA synchronous=%d", as.integer(nsync)))
    }, silent = TRUE)
    
    con
  })

#' @export
#' @rdname dbConnect-SQLiteDriver-method
#' @useDynLib RSQLite RS_SQLite_cloneConnection
setMethod("dbConnect", "SQLiteConnection", function(drv){
  new.id <- .Call(RS_SQLite_cloneConnection, drv@Id)
  new("SQLiteConnection", Id = new.id)
})


#' @export
#' @rdname dbConnect-SQLiteDriver-method
#' @useDynLib RSQLite RS_SQLite_closeConnection
setMethod("dbDisconnect", "SQLiteConnection", function(conn) {
  if(!isIdCurrent(conn)){
    warning("expired SQLiteConnection")
    return(TRUE)
  }
  .Call(RS_SQLite_closeConnection, conn@Id)
})
