#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom DBItest check_df
#' @importFrom DBItest connect
#' @importFrom DBItest dbi_generics
#' @importFrom DBItest expect_all_args_have_default_values
#' @importFrom DBItest expect_ellipsis_in_formals
#' @importFrom DBItest expect_equal_df
#' @importFrom DBItest expect_has_class_method
#' @importFrom DBItest expect_invisible_true
#' @importFrom DBItest get_default_context
#' @importFrom DBItest get_key_methods
#' @importFrom DBItest get_penguins
#' @importFrom DBItest get_pkg_path
#' @importFrom DBItest get_placeholder_funs
#' @importFrom DBItest get_texts
#' @importFrom DBItest has_utf8_or_ascii_encoding
#' @importFrom DBItest local_connection
#' @importFrom DBItest local_remove_test_table
#' @importFrom DBItest local_result
#' @importFrom DBItest new_bind_tester_extra
#' @importFrom DBItest package_name
#' @importFrom DBItest random_table_name
#' @importFrom DBItest s4_methods
#' @importFrom DBItest sql_union
#' @importFrom DBItest test_data_type
#' @importFrom DBItest test_select
#' @importFrom DBItest test_select_bind
#' @importFrom DBItest test_select_with_null
#' @importFrom DBItest test_table_roundtrip
#' @importFrom DBItest test_table_roundtrip_one
#' @importFrom DBItest trivial_df
#' @importFrom DBItest trivial_query
#' @importFrom DBItest trivial_values
#' @importFrom DBItest try_silent
#' @importFrom DBItest unrowname
#' @importFrom rlang %||%
#' @importFrom rlang :=
#' @importFrom rlang abort
#' @importFrom rlang as_function
#' @importFrom rlang enexpr
#' @importFrom rlang enquo
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang expr
#' @importFrom rlang has_length
#' @importFrom rlang is_interactive
#' @importFrom rlang list2
#' @importFrom rlang local_options
#' @importFrom rlang quo
#' @importFrom rlang seq2
#' @importFrom rlang set_names
## usethis namespace: end
NULL
